name: Deploy

on:
  release:
    types: [created]

env:
  NODE_VERSION: '14.x'

jobs:
  run-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
      # Test
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: npm install, build
        run: |
          npm install
          # npm run build

      # Deploy
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_SERVER_IUPA }}
#           known_hosts: '# Solo para que no de error...'
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: 'Deploy Server'
        run: ssh ${{ secrets.SSH_HOST }} ${{ secrets.SERVER_DEPLOY_SCRIPT }}
